version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile-Mvc
    ports:
      - ${MVC_WEB_PORT}:80
    networks:
      - backend
    volumes:
      - type: bind
        source: ${MVC_WEB_VOLUME_APPSETTINGS_SOURCE}
        target: /app/appsettings.json
      - type: bind
        source: ${MVC_WEB_VOLUME_LOGS_SOURCE}
        target: /app/log
networks:
  backend:

