version: '3.8'

services:
  db:
    image: "mysql:8.0.0"
    ports:
      - ${DB_PORT}:3306
    volumes:
      - type: bind
        source: ${DB_VOLUME_SOURCE}
        target: /var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      BIND-ADDRESS: 0.0.0.0

  web:
    build: 
      context: .
      dockerfile: Dockerfile-Ids
    ports:
      - ${WEB_PORT}:80
    networks:
      - backend
    volumes:
      - type: bind
        source: ${WEB_VOLUME_APPSETTINGS_SOURCE}
        target: /app/appsettings.json
      - type: bind
        source: D:/dockervolumes/minishopids/log
        target: /app/log
    environment:
      INITDB: initdb
      CONNECTIONSTRING: ${WEB_CONNECTIONSTRING}
    depends_on:
      - db

networks:
  backend:

