version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile-Mvc
    ports:
      - ${WEB_PORT}:80
    networks:
      - backend
    volumes:
      - type: bind
        source: ${WEB_VOLUME_APPSETTINGS_SOURCE}
        target: /app/appsettings.json

networks:
  backend:

