version: '3.7'

services:
  db:
    image: "mysql:8.0.0"
    ports:
      - 3307:3306
    volumes:
      - D:/dockervolumes/minishopidsdata/db:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      BIND-ADDRESS: 0.0.0.0

  dbinit:
    build: 
      context: .
      dockerfile: Dockerfile-Ids-UseCompose
    networks:
      - backend
    environment:
      INITDB: initdb
      CONNECTIONSTRING: server=db;database=MiniShopIdsDB;uid=root;pwd=123456;SslMode=None;ConnectionReset=false;connect timeout=3600
    depends_on:
      - db      

  web:
    build: 
      context: .
      dockerfile: Dockerfile-Ids-UseCompose
    ports:
      - 8000:80
    networks:
      - backend
    environment:
      CONNECTIONSTRING: server=db;database=MiniShopIdsDB;uid=root;pwd=123456;SslMode=None;ConnectionReset=false;connect timeout=3600
    depends_on:
      - db

networks:
  backend:
