#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
COPY MiniShop.Ids/node_modules/wait-for-it.sh/bin/wait-for-it /app/wait-for-it.sh
RUN chmod +x /app/wait-for-it.sh
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["MiniShop.Ids/MiniShop.Ids.csproj", "MiniShop.Ids/"]
COPY ["CommonTools.Core/CommonTools.Core.csproj", "CommonTools.Core/"]
COPY ["Logging.Serilog/Logging.Serilog.csproj", "Logging.Serilog/"]
RUN dotnet restore "MiniShop.Ids/MiniShop.Ids.csproj"
COPY . .
WORKDIR "/src/MiniShop.Ids"
RUN dotnet build "MiniShop.Ids.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MiniShop.Ids.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV WAITHOST=db WAITPORT=3306
ENTRYPOINT ["./wait-for-it.sh ${WAITHOST}:${WAITPORT} --timeout=0 \ && exec dotnet MiniShop.Ids.dll"]