// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniShopAdmin.Api.Models.Code;

namespace MiniShopAdmin.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220124054057_InitMigrations")]
    partial class InitMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MiniShopAdmin.Api.Models.RenewPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("OperatorName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RenewPackage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2022, 1, 24, 13, 40, 56, 73, DateTimeKind.Local).AddTicks(8431),
                            ModifiedTime = new DateTime(2022, 1, 24, 13, 40, 56, 76, DateTimeKind.Local).AddTicks(5401),
                            Name = "半年",
                            Price = 299m
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2022, 1, 24, 13, 40, 56, 78, DateTimeKind.Local).AddTicks(2492),
                            ModifiedTime = new DateTime(2022, 1, 24, 13, 40, 56, 78, DateTimeKind.Local).AddTicks(2512),
                            Name = "一年",
                            Price = 499m
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(2022, 1, 24, 13, 40, 56, 78, DateTimeKind.Local).AddTicks(4836),
                            ModifiedTime = new DateTime(2022, 1, 24, 13, 40, 56, 78, DateTimeKind.Local).AddTicks(4841),
                            Name = "两年",
                            Price = 799m
                        },
                        new
                        {
                            Id = 4,
                            CreatedTime = new DateTime(2022, 1, 24, 13, 40, 56, 78, DateTimeKind.Local).AddTicks(7544),
                            ModifiedTime = new DateTime(2022, 1, 24, 13, 40, 56, 78, DateTimeKind.Local).AddTicks(7553),
                            Name = "三年",
                            Price = 1099m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
